%% Plot SI Figure S2 a-f in the E and I collective-phase planes
clear; clc; clear functions;

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir), scriptDir = pwd; end
figureDir = fileparts(scriptDir);
dataDir = fullfile(figureDir, 'data');
outputDir = fullfile(figureDir, 'output');
addpath(scriptDir);

gIEList = [0.02784, 0.15517, 0.28966];
spaces = struct( ...
    'dataFolder', {'Eplane', 'Iplane'}, ...
    'fileTag', {'REcospsiE_REsinpsiE', 'RIcospsiI_RIsinpsiI'}, ...
    'outputFolder', {'S2_a_c_Eplane', 'S2_d_f_Iplane'}, ...
    'view', {[26.644919786096253, 80.576300578034676], ...
             [26.644919786096253, 80.576300578034676]});

for iSpace = 1:numel(spaces)
    for gIE = gIEList
        inFile = fullfile(dataDir, spaces(iSpace).dataFolder, ...
            sprintf('analysis_%s_gIE=%.5f.mat', spaces(iSpace).fileTag, gIE));
        if ~exist(inFile, 'file')
            error('Required data file not found:\n  %s', inFile);
        end
        S = load(inFile, 'landscape', 'flux', 'param');
        plot_landscape_flux_phase_space_3D( ...
            S.landscape, S.flux, S.param, ...
            fullfile(outputDir, spaces(iSpace).outputFolder), ...
            'Visible', 'off', 'Save', true, 'PlotFluxArrows', true, ...
            'Step', [6 6], 'ArrowBase', 0.060, ...
            'ArrowLineWidth', 2.4, 'ArrowColor', [1 1 1], ...
            'SurfaceAlpha', 0.95, 'UCap', 14, ...
            'FluxPThreshold', 1e-4, 'View', spaces(iSpace).view, ...
            'ZOffset', 0.18, 'AxisFontSize', 28, 'LabelFontSize', 34, ...
            'ShowTitle', false, 'XLim', [-1 1], 'YLim', [-1 1]);
    end
end

fprintf('SI Figure S2 a-f saved under:\n  %s\n', outputDir);
