%% Plot Figure 3D: landscapes and fluxes in R, collective-phase, and PCA spaces
clear; clc; clear functions;

scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir), scriptDir = pwd; end
figureDir = fileparts(scriptDir);
dataDir = fullfile(figureDir, 'data');
outputDir = fullfile(figureDir, 'output', 'D');
addpath(scriptDir);

gIEList = [0.02784, 0.15517, 0.28966];

for gIE = gIEList
    param = struct('gIE', gIE);

    rFile = fullfile(dataDir, 'R', ...
        sprintf('analysis_R_gIE=%.5f.mat', gIE));
    require_file(rFile);
    SR = load(rFile, 'landscape_R', 'flux_R');
    creature_figure_landscape_flux_3D( ...
        SR.landscape_R, SR.flux_R, param, fullfile(outputDir, 'R'), ...
        'Visible', 'off', 'Save', true, 'Step', [5 5], ...
        'ArrowBase', 0.06, 'ArrowGain', 3, 'ZOffset', 0.09, ...
        'View', [561.2894590375522, 57.241918325921333]);

    phaseFile = fullfile(dataDir, 'CosPhase', ...
        sprintf('analysis_cospsiE_cospsiI_gIE=%.5f.mat', gIE));
    require_file(phaseFile);
    SPhase = load(phaseFile, 'landscape', 'flux', 'param');
    plot_landscape_flux_phase_space_3D( ...
        SPhase.landscape, SPhase.flux, SPhase.param, ...
        fullfile(outputDir, 'CosPhase'), ...
        'Visible', 'off', 'Save', true, 'PlotFluxArrows', true, ...
        'Step', [6 6], 'ArrowBase', 0.060, 'ArrowLineWidth', 2.4, ...
        'ArrowColor', [1 1 1], 'SurfaceAlpha', 0.95, 'UCap', 14, ...
        'FluxPThreshold', 1e-4, ...
        'View', [82.852592860239923, 65.999377271914668], ...
        'ZOffset', 0.18, 'AxisFontSize', 28, 'LabelFontSize', 34, ...
        'ShowTitle', false, 'XLim', [-1 1], 'YLim', [-1 1]);

    pcaFile = fullfile(dataDir, 'PCA', ...
        sprintf('analysis_PCA_gIE=%.5f.mat', gIE));
    require_file(pcaFile);
    SPCA = load(pcaFile, 'landscape_pca', 'flux_pca');
    creature_figure_landscape_flux_PCA_3D( ...
        SPCA.landscape_pca, SPCA.flux_pca, param, ...
        fullfile(outputDir, 'PCA'), ...
        'Visible', 'off', 'Save', true, 'Step', [17 17], ...
        'ArrowBase', 0.2, 'ArrowGain', 3, ...
        'View', [26.083829612519139, 78.009923709460921], ...
        'ZOffset', 0.1);
end

fprintf('Figure 3D panels saved under:\n  %s\n', outputDir);

function require_file(filePath)
if ~exist(filePath, 'file')
    error('Required data file not found:\n  %s', filePath);
end
end
